//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryDetail
    {
        public long Rid { get; set; }
        public System.Guid BeneficiaryId { get; set; }
        public int YearId { get; set; }
        public int Occupation { get; set; }
        public string OccupationDescription { get; set; }
        public decimal TotalLandinDecimal { get; set; }
        public Nullable<decimal> YearlyIncome { get; set; }
        public Nullable<byte> FamilyMember { get; set; }
        public Nullable<byte> FamilyEarningMember { get; set; }
        public Nullable<bool> IsVGDBenefitted { get; set; }
        public Nullable<int> VictimByDisaster { get; set; }
        public Nullable<int> GetSupportFrom { get; set; }
        public Nullable<int> GovtSupport { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
    }
}
