//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.PermissionRoles = new HashSet<PermissionRole>();
            this.PermissionUsers = new HashSet<PermissionUser>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public bool EvidenceRead { get; set; }
        public bool EvidenceWrite { get; set; }
        public bool EvidenceUpdate { get; set; }
        public bool EvidenceDelete { get; set; }
        public bool EvidenceDownload { get; set; }
        public bool UserView { get; set; }
        public bool UserEdit { get; set; }
        public bool UserDelete { get; set; }
    
        public virtual ICollection<PermissionRole> PermissionRoles { get; set; }
        public virtual ICollection<PermissionUser> PermissionUsers { get; set; }
    }
}
