//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionRole
    {
        public long Id { get; set; }
        public string RoleId { get; set; }
        public bool GrantPermisiion { get; set; }
        public long PermissionsId { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
